# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 24.4.0.61
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import extremecloudiq
from extremecloudiq.models.xiq_attach_up_assignment_request import XiqAttachUPAssignmentRequest  # noqa: E501
from extremecloudiq.rest import ApiException

class TestXiqAttachUPAssignmentRequest(unittest.TestCase):
    """XiqAttachUPAssignmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test XiqAttachUPAssignmentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = extremecloudiq.models.xiq_attach_up_assignment_request.XiqAttachUPAssignmentRequest()  # noqa: E501
        if include_optional :
            return XiqAttachUPAssignmentRequest(
                user_profile_assignment_rules = [
                    extremecloudiq.models.xiq_attach_up_assignment_entry.XiqAttachUPAssignmentEntry(
                        user_profile_id = 56, 
                        user_profile_assignment_id = 56, )
                    ], 
                enable_user_profile_assignment = True, 
                enable_radius_attribute_user_profile_assignment = True, 
                attribute_type = 'TUNNEL', 
                attribute_key = 56, 
                default_radius_client_object_id = 56
            )
        else :
            return XiqAttachUPAssignmentRequest(
        )

    def testXiqAttachUPAssignmentRequest(self):
        """Test XiqAttachUPAssignmentRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
