# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 23.3.0.35
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import extremecloudiq
from extremecloudiq.api.copilot___connectivity_experience_api import CopilotConnectivityExperienceApi  # noqa: E501
from extremecloudiq.rest import ApiException


class TestCopilotConnectivityExperienceApi(unittest.TestCase):
    """CopilotConnectivityExperienceApi unit test stubs"""

    def setUp(self):
        self.api = extremecloudiq.api.copilot___connectivity_experience_api.CopilotConnectivityExperienceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_wired_connectivity_experience(self):
        """Test case for get_wired_connectivity_experience

        """
        pass

    def test_get_wired_events(self):
        """Test case for get_wired_events

        """
        pass

    def test_get_wired_hardware(self):
        """Test case for get_wired_hardware

        """
        pass

    def test_get_wired_quality_index(self):
        """Test case for get_wired_quality_index

        """
        pass

    def test_get_wireless_apps(self):
        """Test case for get_wireless_apps

        """
        pass

    def test_get_wireless_connectivity_experience(self):
        """Test case for get_wireless_connectivity_experience

        """
        pass

    def test_get_wireless_events(self):
        """Test case for get_wireless_events

        """
        pass

    def test_get_wireless_performance(self):
        """Test case for get_wireless_performance

        """
        pass

    def test_get_wireless_quality_index(self):
        """Test case for get_wireless_quality_index

        """
        pass

    def test_get_wireless_time_to_connect(self):
        """Test case for get_wireless_time_to_connect

        """
        pass

    def test_get_wireless_views(self):
        """Test case for get_wireless_views

        """
        pass


if __name__ == '__main__':
    unittest.main()
