# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 24.2.0.39
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import extremecloudiq
from extremecloudiq.models.paged_xiq_location_tree_device import PagedXiqLocationTreeDevice  # noqa: E501
from extremecloudiq.rest import ApiException

class TestPagedXiqLocationTreeDevice(unittest.TestCase):
    """PagedXiqLocationTreeDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PagedXiqLocationTreeDevice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = extremecloudiq.models.paged_xiq_location_tree_device.PagedXiqLocationTreeDevice()  # noqa: E501
        if include_optional :
            return PagedXiqLocationTreeDevice(
                page = 56, 
                count = 56, 
                total_pages = 56, 
                total_count = 56, 
                data = [
                    extremecloudiq.models.xiq_location_tree_device.XiqLocationTreeDevice(
                        device_name = '0', 
                        serial_number = '0', 
                        mac_address = '0', 
                        device_function = '0', 
                        product_type = '0', 
                        ip_address = '0', 
                        location_id = 56, 
                        map_name = '0', 
                        x = 1.337, 
                        y = 1.337, 
                        scale_x = 1.337, 
                        scale_y = 1.337, )
                    ]
            )
        else :
            return PagedXiqLocationTreeDevice(
                page = 56,
                count = 56,
                total_pages = 56,
                total_count = 56,
        )

    def testPagedXiqLocationTreeDevice(self):
        """Test PagedXiqLocationTreeDevice"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
