# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 24.4.0.61
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import extremecloudiq
from extremecloudiq.models.xiq_mac_object_type import XiqMacObjectType  # noqa: E501
from extremecloudiq.rest import ApiException

class TestXiqMacObjectType(unittest.TestCase):
    """XiqMacObjectType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test XiqMacObjectType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = extremecloudiq.models.xiq_mac_object_type.XiqMacObjectType()  # noqa: E501
        if include_optional :
            return XiqMacObjectType(
            )
        else :
            return XiqMacObjectType(
        )

    def testXiqMacObjectType(self):
        """Test XiqMacObjectType"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
