# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 24.6.0.74
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import extremecloudiq
from extremecloudiq.api.configuration___deployment_api import ConfigurationDeploymentApi  # noqa: E501
from extremecloudiq.rest import ApiException


class TestConfigurationDeploymentApi(unittest.TestCase):
    """ConfigurationDeploymentApi unit test stubs"""

    def setUp(self):
        self.api = extremecloudiq.api.configuration___deployment_api.ConfigurationDeploymentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_firmware_upgrade_schedule(self):
        """Test case for delete_firmware_upgrade_schedule

        Delete the deployment schedule by ID  # noqa: E501
        """
        pass

    def test_deploy_config(self):
        """Test case for deploy_config

        [LRO] Push configuration and upgrade firmware  # noqa: E501
        """
        pass

    def test_get_deploy_overview(self):
        """Test case for get_deploy_overview

        Get configuration deployment overview  # noqa: E501
        """
        pass

    def test_get_deploy_status(self):
        """Test case for get_deploy_status

        Get configuration deployment status  # noqa: E501
        """
        pass

    def test_get_deployment_by_id_status(self):
        """Test case for get_deployment_by_id_status

        Get firmware deployment status by ID  # noqa: E501
        """
        pass

    def test_get_deployment_details_by_id(self):
        """Test case for get_deployment_details_by_id

        Get deployment details by Id  # noqa: E501
        """
        pass

    def test_get_device_firmware_metadatas(self):
        """Test case for get_device_firmware_metadatas

        Get device firmware metadatas  # noqa: E501
        """
        pass

    def test_get_list_of_deployments(self):
        """Test case for get_list_of_deployments

        Get list of deployments  # noqa: E501
        """
        pass

    def test_update_firmware_upgrade_schedule(self):
        """Test case for update_firmware_upgrade_schedule

        Update schedule with deployment ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
