# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.2.0.123
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import extremecloudiq
from extremecloudiq.model.xiq_wireless_performance_retries_entity import XiqWirelessPerformanceRetriesEntity
from extremecloudiq import configuration


class TestXiqWirelessPerformanceRetriesEntity(unittest.TestCase):
    """XiqWirelessPerformanceRetriesEntity unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
