# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.2.0.123
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import extremecloudiq
from extremecloudiq.model.xiq_user import XiqUser
from extremecloudiq import configuration


class TestXiqUser(unittest.TestCase):
    """XiqUser unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
