# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.2.0.123
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from extremecloudiq import schemas  # noqa: F401


class RttsSessionDevices(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class deviceIds(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'deviceIds':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class clientMacs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'clientMacs':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class packetType(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ALL": "ALL",
                        "DATA": "DATA",
                        "MGT": "MGT",
                        "UNRECOGNIZED": "UNRECOGNIZED",
                    }
                
                @schemas.classproperty
                def ALL(cls):
                    return cls("ALL")
                
                @schemas.classproperty
                def DATA(cls):
                    return cls("DATA")
                
                @schemas.classproperty
                def MGT(cls):
                    return cls("MGT")
                
                @schemas.classproperty
                def UNRECOGNIZED(cls):
                    return cls("UNRECOGNIZED")
            __annotations__ = {
                "deviceIds": deviceIds,
                "clientMacs": clientMacs,
                "packetType": packetType,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deviceIds"]) -> MetaOapg.properties.deviceIds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientMacs"]) -> MetaOapg.properties.clientMacs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["packetType"]) -> MetaOapg.properties.packetType: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["deviceIds", "clientMacs", "packetType", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deviceIds"]) -> typing.Union[MetaOapg.properties.deviceIds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientMacs"]) -> typing.Union[MetaOapg.properties.clientMacs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["packetType"]) -> typing.Union[MetaOapg.properties.packetType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["deviceIds", "clientMacs", "packetType", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        deviceIds: typing.Union[MetaOapg.properties.deviceIds, list, tuple, schemas.Unset] = schemas.unset,
        clientMacs: typing.Union[MetaOapg.properties.clientMacs, list, tuple, schemas.Unset] = schemas.unset,
        packetType: typing.Union[MetaOapg.properties.packetType, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RttsSessionDevices':
        return super().__new__(
            cls,
            *_args,
            deviceIds=deviceIds,
            clientMacs=clientMacs,
            packetType=packetType,
            _configuration=_configuration,
            **kwargs,
        )
