# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.5.1-15
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from extremecloudiq import schemas  # noqa: F401


class XiqQoeDiagnosticsTableDataFilters(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    metrics
    """


    class MetaOapg:
        required = {
            "floor_ids",
            "start_time",
            "site_ids",
            "sort_field",
            "end_time",
            "building_ids",
            "metrics",
            "sort_order",
        }
        
        class properties:
        
            @staticmethod
            def metrics() -> typing.Type['XiqQoeDiagnosticsMetrics']:
                return XiqQoeDiagnosticsMetrics
            
            
            class site_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'site_ids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class floor_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'floor_ids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class building_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'building_ids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            start_time = schemas.Int64Schema
            end_time = schemas.Int64Schema
            
            
            class sort_field(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "TIME_STAMP": "TIME_STAMP",
                        "MAC": "MAC",
                        "HOSTNAME": "HOSTNAME",
                        "SESSION_DURATION": "SESSION_DURATION",
                        "CONNECTED_TIME": "CONNECTED_TIME",
                        "DISCONNECTED_TIME": "DISCONNECTED_TIME",
                        "TOTAL_DATA_USAGE": "TOTAL_DATA_USAGE",
                        "RELATIVE_TIME": "RELATIVE_TIME",
                        "TOTAL_POWER_USAGE": "TOTAL_POWER_USAGE",
                        "IDLE_POWER": "IDLE_POWER",
                        "MAX_POWER": "MAX_POWER",
                        "AVG_POWER": "AVG_POWER",
                        "APPLICATION_USAGE": "APPLICATION_USAGE",
                        "PERCENTAGE_CHANNEL_UTILIZATION": "PERCENTAGE_CHANNEL_UTILIZATION",
                        "PERCENTAGE_AIRTIME_UTILIZATION": "PERCENTAGE_AIRTIME_UTILIZATION",
                        "ERROR_TIMESTAMP": "ERROR_TIMESTAMP",
                        "NETWORK_USAGE": "NETWORK_USAGE",
                        "RETRY_COUNT": "RETRY_COUNT",
                        "FAILED_ROAM_DATE_AND_TIME": "FAILED_ROAM_DATE_AND_TIME",
                        "LAST_AP_HOSTNAME": "LAST_AP_HOSTNAME",
                        "FROM_AP_HOSTNAME": "FROM_AP_HOSTNAME",
                        "TO_AP_HOSTNAME": "TO_AP_HOSTNAME",
                        "FAILURE_TIME_STAMP": "FAILURE_TIME_STAMP",
                        "PORT_SPEED": "PORT_SPEED",
                        "DEVICE_DOWN_DATE_AND_TIME": "DEVICE_DOWN_DATE_AND_TIME",
                        "DOWN_TIME": "DOWN_TIME",
                        "LOGIN_DATE_AND_TIME": "LOGIN_DATE_AND_TIME",
                        "LOGIN_DURATION": "LOGIN_DURATION",
                        "AUTHENTICATION_DATE_TIME": "AUTHENTICATION_DATE_TIME",
                        "USB_POWER_CONSUMED": "USB_POWER_CONSUMED",
                        "ALERT_DATE_TIME": "ALERT_DATE_TIME",
                        "DFS_CHANNEL_CHANGE_DATE_AND_TIME": "DFS_CHANNEL_CHANGE_DATE_AND_TIME",
                        "ACSP_CHANGE_DATE_AND_TIME": "ACSP_CHANGE_DATE_AND_TIME",
                        "DATE_AND_TIME": "DATE_AND_TIME",
                        "PERCENTAGE_CONGESTION": "PERCENTAGE_CONGESTION",
                    }
                
                @schemas.classproperty
                def TIME_STAMP(cls):
                    return cls("TIME_STAMP")
                
                @schemas.classproperty
                def MAC(cls):
                    return cls("MAC")
                
                @schemas.classproperty
                def HOSTNAME(cls):
                    return cls("HOSTNAME")
                
                @schemas.classproperty
                def SESSION_DURATION(cls):
                    return cls("SESSION_DURATION")
                
                @schemas.classproperty
                def CONNECTED_TIME(cls):
                    return cls("CONNECTED_TIME")
                
                @schemas.classproperty
                def DISCONNECTED_TIME(cls):
                    return cls("DISCONNECTED_TIME")
                
                @schemas.classproperty
                def TOTAL_DATA_USAGE(cls):
                    return cls("TOTAL_DATA_USAGE")
                
                @schemas.classproperty
                def RELATIVE_TIME(cls):
                    return cls("RELATIVE_TIME")
                
                @schemas.classproperty
                def TOTAL_POWER_USAGE(cls):
                    return cls("TOTAL_POWER_USAGE")
                
                @schemas.classproperty
                def IDLE_POWER(cls):
                    return cls("IDLE_POWER")
                
                @schemas.classproperty
                def MAX_POWER(cls):
                    return cls("MAX_POWER")
                
                @schemas.classproperty
                def AVG_POWER(cls):
                    return cls("AVG_POWER")
                
                @schemas.classproperty
                def APPLICATION_USAGE(cls):
                    return cls("APPLICATION_USAGE")
                
                @schemas.classproperty
                def PERCENTAGE_CHANNEL_UTILIZATION(cls):
                    return cls("PERCENTAGE_CHANNEL_UTILIZATION")
                
                @schemas.classproperty
                def PERCENTAGE_AIRTIME_UTILIZATION(cls):
                    return cls("PERCENTAGE_AIRTIME_UTILIZATION")
                
                @schemas.classproperty
                def ERROR_TIMESTAMP(cls):
                    return cls("ERROR_TIMESTAMP")
                
                @schemas.classproperty
                def NETWORK_USAGE(cls):
                    return cls("NETWORK_USAGE")
                
                @schemas.classproperty
                def RETRY_COUNT(cls):
                    return cls("RETRY_COUNT")
                
                @schemas.classproperty
                def FAILED_ROAM_DATE_AND_TIME(cls):
                    return cls("FAILED_ROAM_DATE_AND_TIME")
                
                @schemas.classproperty
                def LAST_AP_HOSTNAME(cls):
                    return cls("LAST_AP_HOSTNAME")
                
                @schemas.classproperty
                def FROM_AP_HOSTNAME(cls):
                    return cls("FROM_AP_HOSTNAME")
                
                @schemas.classproperty
                def TO_AP_HOSTNAME(cls):
                    return cls("TO_AP_HOSTNAME")
                
                @schemas.classproperty
                def FAILURE_TIME_STAMP(cls):
                    return cls("FAILURE_TIME_STAMP")
                
                @schemas.classproperty
                def PORT_SPEED(cls):
                    return cls("PORT_SPEED")
                
                @schemas.classproperty
                def DEVICE_DOWN_DATE_AND_TIME(cls):
                    return cls("DEVICE_DOWN_DATE_AND_TIME")
                
                @schemas.classproperty
                def DOWN_TIME(cls):
                    return cls("DOWN_TIME")
                
                @schemas.classproperty
                def LOGIN_DATE_AND_TIME(cls):
                    return cls("LOGIN_DATE_AND_TIME")
                
                @schemas.classproperty
                def LOGIN_DURATION(cls):
                    return cls("LOGIN_DURATION")
                
                @schemas.classproperty
                def AUTHENTICATION_DATE_TIME(cls):
                    return cls("AUTHENTICATION_DATE_TIME")
                
                @schemas.classproperty
                def USB_POWER_CONSUMED(cls):
                    return cls("USB_POWER_CONSUMED")
                
                @schemas.classproperty
                def ALERT_DATE_TIME(cls):
                    return cls("ALERT_DATE_TIME")
                
                @schemas.classproperty
                def DFS_CHANNEL_CHANGE_DATE_AND_TIME(cls):
                    return cls("DFS_CHANNEL_CHANGE_DATE_AND_TIME")
                
                @schemas.classproperty
                def ACSP_CHANGE_DATE_AND_TIME(cls):
                    return cls("ACSP_CHANGE_DATE_AND_TIME")
                
                @schemas.classproperty
                def DATE_AND_TIME(cls):
                    return cls("DATE_AND_TIME")
                
                @schemas.classproperty
                def PERCENTAGE_CONGESTION(cls):
                    return cls("PERCENTAGE_CONGESTION")
        
            @staticmethod
            def sort_order() -> typing.Type['XiqSortOrder']:
                return XiqSortOrder
            
            
            class bands(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['XiqDiagnosticsBands']:
                        return XiqDiagnosticsBands
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['XiqDiagnosticsBands'], typing.List['XiqDiagnosticsBands']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'bands':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'XiqDiagnosticsBands':
                    return super().__getitem__(i)
            
            
            class contypes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['XiqQoeDiagnosticsConnTypes']:
                        return XiqQoeDiagnosticsConnTypes
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['XiqQoeDiagnosticsConnTypes'], typing.List['XiqQoeDiagnosticsConnTypes']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'contypes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'XiqQoeDiagnosticsConnTypes':
                    return super().__getitem__(i)
            
            
            class devicetypes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['XiqQoeDiagnosticsDeviceTypes']:
                        return XiqQoeDiagnosticsDeviceTypes
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['XiqQoeDiagnosticsDeviceTypes'], typing.List['XiqQoeDiagnosticsDeviceTypes']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'devicetypes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'XiqQoeDiagnosticsDeviceTypes':
                    return super().__getitem__(i)
            
            
            class vlan_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int32Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'vlan_ids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class device_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'device_ids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class ssids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'ssids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class user_names(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'user_names':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class client_macs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'client_macs':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class port_nums(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'port_nums':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class app_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'app_ids':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class channel_nums(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int32Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'channel_nums':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class admin_roles(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.Int64Schema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, decimal.Decimal, int, ]], typing.List[typing.Union[MetaOapg.items, decimal.Decimal, int, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'admin_roles':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            page_no = schemas.Int32Schema
            limit = schemas.Int32Schema
            export_data = schemas.BoolSchema
            search_parameter = schemas.StrSchema
            _async = schemas.BoolSchema
            
            
            class os_types(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'os_types':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            isSSIDSelected = schemas.BoolSchema
            isBandSelected = schemas.BoolSchema
            __annotations__ = {
                "metrics": metrics,
                "site_ids": site_ids,
                "floor_ids": floor_ids,
                "building_ids": building_ids,
                "start_time": start_time,
                "end_time": end_time,
                "sort_field": sort_field,
                "sort_order": sort_order,
                "bands": bands,
                "contypes": contypes,
                "devicetypes": devicetypes,
                "vlan_ids": vlan_ids,
                "device_ids": device_ids,
                "ssids": ssids,
                "user_names": user_names,
                "client_macs": client_macs,
                "port_nums": port_nums,
                "app_ids": app_ids,
                "channel_nums": channel_nums,
                "admin_roles": admin_roles,
                "page_no": page_no,
                "limit": limit,
                "export_data": export_data,
                "search_parameter": search_parameter,
                "async": _async,
                "os_types": os_types,
                "isSSIDSelected": isSSIDSelected,
                "isBandSelected": isBandSelected,
            }
    
    floor_ids: MetaOapg.properties.floor_ids
    start_time: MetaOapg.properties.start_time
    site_ids: MetaOapg.properties.site_ids
    sort_field: MetaOapg.properties.sort_field
    end_time: MetaOapg.properties.end_time
    building_ids: MetaOapg.properties.building_ids
    metrics: 'XiqQoeDiagnosticsMetrics'
    sort_order: 'XiqSortOrder'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metrics"]) -> 'XiqQoeDiagnosticsMetrics': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["site_ids"]) -> MetaOapg.properties.site_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["floor_ids"]) -> MetaOapg.properties.floor_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["building_ids"]) -> MetaOapg.properties.building_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["start_time"]) -> MetaOapg.properties.start_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["end_time"]) -> MetaOapg.properties.end_time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sort_field"]) -> MetaOapg.properties.sort_field: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sort_order"]) -> 'XiqSortOrder': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bands"]) -> MetaOapg.properties.bands: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contypes"]) -> MetaOapg.properties.contypes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["devicetypes"]) -> MetaOapg.properties.devicetypes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vlan_ids"]) -> MetaOapg.properties.vlan_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["device_ids"]) -> MetaOapg.properties.device_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ssids"]) -> MetaOapg.properties.ssids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["user_names"]) -> MetaOapg.properties.user_names: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["client_macs"]) -> MetaOapg.properties.client_macs: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["port_nums"]) -> MetaOapg.properties.port_nums: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["app_ids"]) -> MetaOapg.properties.app_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["channel_nums"]) -> MetaOapg.properties.channel_nums: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["admin_roles"]) -> MetaOapg.properties.admin_roles: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["page_no"]) -> MetaOapg.properties.page_no: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["limit"]) -> MetaOapg.properties.limit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["export_data"]) -> MetaOapg.properties.export_data: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["search_parameter"]) -> MetaOapg.properties.search_parameter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["async"]) -> MetaOapg.properties._async: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["os_types"]) -> MetaOapg.properties.os_types: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isSSIDSelected"]) -> MetaOapg.properties.isSSIDSelected: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["isBandSelected"]) -> MetaOapg.properties.isBandSelected: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["metrics", "site_ids", "floor_ids", "building_ids", "start_time", "end_time", "sort_field", "sort_order", "bands", "contypes", "devicetypes", "vlan_ids", "device_ids", "ssids", "user_names", "client_macs", "port_nums", "app_ids", "channel_nums", "admin_roles", "page_no", "limit", "export_data", "search_parameter", "async", "os_types", "isSSIDSelected", "isBandSelected", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metrics"]) -> 'XiqQoeDiagnosticsMetrics': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["site_ids"]) -> MetaOapg.properties.site_ids: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["floor_ids"]) -> MetaOapg.properties.floor_ids: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["building_ids"]) -> MetaOapg.properties.building_ids: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["start_time"]) -> MetaOapg.properties.start_time: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["end_time"]) -> MetaOapg.properties.end_time: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sort_field"]) -> MetaOapg.properties.sort_field: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sort_order"]) -> 'XiqSortOrder': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bands"]) -> typing.Union[MetaOapg.properties.bands, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contypes"]) -> typing.Union[MetaOapg.properties.contypes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["devicetypes"]) -> typing.Union[MetaOapg.properties.devicetypes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vlan_ids"]) -> typing.Union[MetaOapg.properties.vlan_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["device_ids"]) -> typing.Union[MetaOapg.properties.device_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ssids"]) -> typing.Union[MetaOapg.properties.ssids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["user_names"]) -> typing.Union[MetaOapg.properties.user_names, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["client_macs"]) -> typing.Union[MetaOapg.properties.client_macs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["port_nums"]) -> typing.Union[MetaOapg.properties.port_nums, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["app_ids"]) -> typing.Union[MetaOapg.properties.app_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["channel_nums"]) -> typing.Union[MetaOapg.properties.channel_nums, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["admin_roles"]) -> typing.Union[MetaOapg.properties.admin_roles, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["page_no"]) -> typing.Union[MetaOapg.properties.page_no, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["limit"]) -> typing.Union[MetaOapg.properties.limit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["export_data"]) -> typing.Union[MetaOapg.properties.export_data, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["search_parameter"]) -> typing.Union[MetaOapg.properties.search_parameter, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["async"]) -> typing.Union[MetaOapg.properties._async, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["os_types"]) -> typing.Union[MetaOapg.properties.os_types, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isSSIDSelected"]) -> typing.Union[MetaOapg.properties.isSSIDSelected, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["isBandSelected"]) -> typing.Union[MetaOapg.properties.isBandSelected, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["metrics", "site_ids", "floor_ids", "building_ids", "start_time", "end_time", "sort_field", "sort_order", "bands", "contypes", "devicetypes", "vlan_ids", "device_ids", "ssids", "user_names", "client_macs", "port_nums", "app_ids", "channel_nums", "admin_roles", "page_no", "limit", "export_data", "search_parameter", "async", "os_types", "isSSIDSelected", "isBandSelected", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        floor_ids: typing.Union[MetaOapg.properties.floor_ids, list, tuple, ],
        start_time: typing.Union[MetaOapg.properties.start_time, decimal.Decimal, int, ],
        site_ids: typing.Union[MetaOapg.properties.site_ids, list, tuple, ],
        sort_field: typing.Union[MetaOapg.properties.sort_field, str, ],
        end_time: typing.Union[MetaOapg.properties.end_time, decimal.Decimal, int, ],
        building_ids: typing.Union[MetaOapg.properties.building_ids, list, tuple, ],
        metrics: 'XiqQoeDiagnosticsMetrics',
        sort_order: 'XiqSortOrder',
        bands: typing.Union[MetaOapg.properties.bands, list, tuple, schemas.Unset] = schemas.unset,
        contypes: typing.Union[MetaOapg.properties.contypes, list, tuple, schemas.Unset] = schemas.unset,
        devicetypes: typing.Union[MetaOapg.properties.devicetypes, list, tuple, schemas.Unset] = schemas.unset,
        vlan_ids: typing.Union[MetaOapg.properties.vlan_ids, list, tuple, schemas.Unset] = schemas.unset,
        device_ids: typing.Union[MetaOapg.properties.device_ids, list, tuple, schemas.Unset] = schemas.unset,
        ssids: typing.Union[MetaOapg.properties.ssids, list, tuple, schemas.Unset] = schemas.unset,
        user_names: typing.Union[MetaOapg.properties.user_names, list, tuple, schemas.Unset] = schemas.unset,
        client_macs: typing.Union[MetaOapg.properties.client_macs, list, tuple, schemas.Unset] = schemas.unset,
        port_nums: typing.Union[MetaOapg.properties.port_nums, list, tuple, schemas.Unset] = schemas.unset,
        app_ids: typing.Union[MetaOapg.properties.app_ids, list, tuple, schemas.Unset] = schemas.unset,
        channel_nums: typing.Union[MetaOapg.properties.channel_nums, list, tuple, schemas.Unset] = schemas.unset,
        admin_roles: typing.Union[MetaOapg.properties.admin_roles, list, tuple, schemas.Unset] = schemas.unset,
        page_no: typing.Union[MetaOapg.properties.page_no, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        limit: typing.Union[MetaOapg.properties.limit, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        export_data: typing.Union[MetaOapg.properties.export_data, bool, schemas.Unset] = schemas.unset,
        search_parameter: typing.Union[MetaOapg.properties.search_parameter, str, schemas.Unset] = schemas.unset,
        os_types: typing.Union[MetaOapg.properties.os_types, list, tuple, schemas.Unset] = schemas.unset,
        isSSIDSelected: typing.Union[MetaOapg.properties.isSSIDSelected, bool, schemas.Unset] = schemas.unset,
        isBandSelected: typing.Union[MetaOapg.properties.isBandSelected, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'XiqQoeDiagnosticsTableDataFilters':
        return super().__new__(
            cls,
            *_args,
            floor_ids=floor_ids,
            start_time=start_time,
            site_ids=site_ids,
            sort_field=sort_field,
            end_time=end_time,
            building_ids=building_ids,
            metrics=metrics,
            sort_order=sort_order,
            bands=bands,
            contypes=contypes,
            devicetypes=devicetypes,
            vlan_ids=vlan_ids,
            device_ids=device_ids,
            ssids=ssids,
            user_names=user_names,
            client_macs=client_macs,
            port_nums=port_nums,
            app_ids=app_ids,
            channel_nums=channel_nums,
            admin_roles=admin_roles,
            page_no=page_no,
            limit=limit,
            export_data=export_data,
            search_parameter=search_parameter,
            os_types=os_types,
            isSSIDSelected=isSSIDSelected,
            isBandSelected=isBandSelected,
            _configuration=_configuration,
            **kwargs,
        )

from extremecloudiq.model.xiq_diagnostics_bands import XiqDiagnosticsBands
from extremecloudiq.model.xiq_qoe_diagnostics_conn_types import XiqQoeDiagnosticsConnTypes
from extremecloudiq.model.xiq_qoe_diagnostics_device_types import XiqQoeDiagnosticsDeviceTypes
from extremecloudiq.model.xiq_qoe_diagnostics_metrics import XiqQoeDiagnosticsMetrics
from extremecloudiq.model.xiq_sort_order import XiqSortOrder
