# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.2.0.123
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from extremecloudiq import schemas  # noqa: F401


class XiqAtpDeviceStatsEntity(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    ExtremeCloud IQ Data Point
    """


    class MetaOapg:
        required = {
            "timestamp",
        }
        
        class properties:
            timestamp = schemas.Int64Schema
            avg_cpu = schemas.NumberSchema
            avg_memory = schemas.NumberSchema
            avg_client_count = schemas.Int32Schema
            __annotations__ = {
                "timestamp": timestamp,
                "avg_cpu": avg_cpu,
                "avg_memory": avg_memory,
                "avg_client_count": avg_client_count,
            }
    
    timestamp: MetaOapg.properties.timestamp
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["avg_cpu"]) -> MetaOapg.properties.avg_cpu: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["avg_memory"]) -> MetaOapg.properties.avg_memory: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["avg_client_count"]) -> MetaOapg.properties.avg_client_count: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["timestamp", "avg_cpu", "avg_memory", "avg_client_count", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timestamp"]) -> MetaOapg.properties.timestamp: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["avg_cpu"]) -> typing.Union[MetaOapg.properties.avg_cpu, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["avg_memory"]) -> typing.Union[MetaOapg.properties.avg_memory, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["avg_client_count"]) -> typing.Union[MetaOapg.properties.avg_client_count, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["timestamp", "avg_cpu", "avg_memory", "avg_client_count", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        timestamp: typing.Union[MetaOapg.properties.timestamp, decimal.Decimal, int, ],
        avg_cpu: typing.Union[MetaOapg.properties.avg_cpu, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        avg_memory: typing.Union[MetaOapg.properties.avg_memory, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        avg_client_count: typing.Union[MetaOapg.properties.avg_client_count, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'XiqAtpDeviceStatsEntity':
        return super().__new__(
            cls,
            *_args,
            timestamp=timestamp,
            avg_cpu=avg_cpu,
            avg_memory=avg_memory,
            avg_client_count=avg_client_count,
            _configuration=_configuration,
            **kwargs,
        )
