# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.3.0.140
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from extremecloudiq import schemas  # noqa: F401


class XiqWiredClientHealthFilter(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The filters available for client health grid
    """
    
    @schemas.classproperty
    def IP_CONNECTIVITY_ISSUES_UNASSIGNED_IP(cls):
        return cls("IP_CONNECTIVITY_ISSUES_UNASSIGNED_IP")
    
    @schemas.classproperty
    def IP_CONNECTIVITY_ISSUES_SELF_ASSIGNED_IP(cls):
        return cls("IP_CONNECTIVITY_ISSUES_SELF_ASSIGNED_IP")
    
    @schemas.classproperty
    def IP_CONNECTIVITY_ISSUES_VALID_IP(cls):
        return cls("IP_CONNECTIVITY_ISSUES_VALID_IP")
    
    @schemas.classproperty
    def PORT_CONGESTION_UNHEALTHY(cls):
        return cls("PORT_CONGESTION_UNHEALTHY")
    
    @schemas.classproperty
    def PORT_CONGESTION_HEALTHY(cls):
        return cls("PORT_CONGESTION_HEALTHY")
    
    @schemas.classproperty
    def TRAFFIC_ANOMALIES_UNHEALTHY(cls):
        return cls("TRAFFIC_ANOMALIES_UNHEALTHY")
    
    @schemas.classproperty
    def TRAFFIC_ANOMALIES_HEALTHY(cls):
        return cls("TRAFFIC_ANOMALIES_HEALTHY")
    
    @schemas.classproperty
    def PORT_ERRORS_UNHEALTHY(cls):
        return cls("PORT_ERRORS_UNHEALTHY")
    
    @schemas.classproperty
    def PORT_ERRORS_HEALTHY(cls):
        return cls("PORT_ERRORS_HEALTHY")
    
    @schemas.classproperty
    def CLIENT_UNHEALTHY(cls):
        return cls("CLIENT_UNHEALTHY")
