# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.2.0.123
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from extremecloudiq import schemas  # noqa: F401


class XiqChannelUtilizationDetails(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The value for Channel Utilization Details
    """


    class MetaOapg:
        
        class properties:
            interference_percentage = schemas.Int32Schema
            tx_retries_percentage = schemas.Int32Schema
            rx_retries_percentage = schemas.Int32Schema
            __annotations__ = {
                "interference_percentage": interference_percentage,
                "tx_retries_percentage": tx_retries_percentage,
                "rx_retries_percentage": rx_retries_percentage,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["interference_percentage"]) -> MetaOapg.properties.interference_percentage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tx_retries_percentage"]) -> MetaOapg.properties.tx_retries_percentage: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["rx_retries_percentage"]) -> MetaOapg.properties.rx_retries_percentage: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["interference_percentage", "tx_retries_percentage", "rx_retries_percentage", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["interference_percentage"]) -> typing.Union[MetaOapg.properties.interference_percentage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tx_retries_percentage"]) -> typing.Union[MetaOapg.properties.tx_retries_percentage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["rx_retries_percentage"]) -> typing.Union[MetaOapg.properties.rx_retries_percentage, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["interference_percentage", "tx_retries_percentage", "rx_retries_percentage", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        interference_percentage: typing.Union[MetaOapg.properties.interference_percentage, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        tx_retries_percentage: typing.Union[MetaOapg.properties.tx_retries_percentage, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        rx_retries_percentage: typing.Union[MetaOapg.properties.rx_retries_percentage, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'XiqChannelUtilizationDetails':
        return super().__new__(
            cls,
            *_args,
            interference_percentage=interference_percentage,
            tx_retries_percentage=tx_retries_percentage,
            rx_retries_percentage=rx_retries_percentage,
            _configuration=_configuration,
            **kwargs,
        )
