# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 23.3.0.35
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from extremecloudiq.configuration import Configuration


class XiqEmailLog(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'username': 'str',
        'org_id': 'int',
        'timestamp': 'int',
        'user_id': 'int',
        'customer_id': 'str',
        'approver_email': 'str',
        'status': 'str'
    }

    attribute_map = {
        'id': 'id',
        'username': 'username',
        'org_id': 'org_id',
        'timestamp': 'timestamp',
        'user_id': 'user_id',
        'customer_id': 'customer_id',
        'approver_email': 'approver_email',
        'status': 'status'
    }

    def __init__(self, id=None, username=None, org_id=None, timestamp=None, user_id=None, customer_id=None, approver_email=None, status=None, local_vars_configuration=None):  # noqa: E501
        """XiqEmailLog - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._username = None
        self._org_id = None
        self._timestamp = None
        self._user_id = None
        self._customer_id = None
        self._approver_email = None
        self._status = None
        self.discriminator = None

        self.id = id
        if username is not None:
            self.username = username
        if org_id is not None:
            self.org_id = org_id
        if timestamp is not None:
            self.timestamp = timestamp
        if user_id is not None:
            self.user_id = user_id
        if customer_id is not None:
            self.customer_id = customer_id
        if approver_email is not None:
            self.approver_email = approver_email
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this XiqEmailLog.  # noqa: E501

        The Email log id  # noqa: E501

        :return: The id of this XiqEmailLog.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this XiqEmailLog.

        The Email log id  # noqa: E501

        :param id: The id of this XiqEmailLog.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def username(self):
        """Gets the username of this XiqEmailLog.  # noqa: E501

        The username  # noqa: E501

        :return: The username of this XiqEmailLog.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this XiqEmailLog.

        The username  # noqa: E501

        :param username: The username of this XiqEmailLog.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def org_id(self):
        """Gets the org_id of this XiqEmailLog.  # noqa: E501

        The org id  # noqa: E501

        :return: The org_id of this XiqEmailLog.  # noqa: E501
        :rtype: int
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this XiqEmailLog.

        The org id  # noqa: E501

        :param org_id: The org_id of this XiqEmailLog.  # noqa: E501
        :type: int
        """

        self._org_id = org_id

    @property
    def timestamp(self):
        """Gets the timestamp of this XiqEmailLog.  # noqa: E501

        The email log timestamp  # noqa: E501

        :return: The timestamp of this XiqEmailLog.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this XiqEmailLog.

        The email log timestamp  # noqa: E501

        :param timestamp: The timestamp of this XiqEmailLog.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def user_id(self):
        """Gets the user_id of this XiqEmailLog.  # noqa: E501

        The user id  # noqa: E501

        :return: The user_id of this XiqEmailLog.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this XiqEmailLog.

        The user id  # noqa: E501

        :param user_id: The user_id of this XiqEmailLog.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def customer_id(self):
        """Gets the customer_id of this XiqEmailLog.  # noqa: E501

        The customer id  # noqa: E501

        :return: The customer_id of this XiqEmailLog.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this XiqEmailLog.

        The customer id  # noqa: E501

        :param customer_id: The customer_id of this XiqEmailLog.  # noqa: E501
        :type: str
        """

        self._customer_id = customer_id

    @property
    def approver_email(self):
        """Gets the approver_email of this XiqEmailLog.  # noqa: E501

        The approver Email  # noqa: E501

        :return: The approver_email of this XiqEmailLog.  # noqa: E501
        :rtype: str
        """
        return self._approver_email

    @approver_email.setter
    def approver_email(self, approver_email):
        """Sets the approver_email of this XiqEmailLog.

        The approver Email  # noqa: E501

        :param approver_email: The approver_email of this XiqEmailLog.  # noqa: E501
        :type: str
        """

        self._approver_email = approver_email

    @property
    def status(self):
        """Gets the status of this XiqEmailLog.  # noqa: E501

        The email log status  # noqa: E501

        :return: The status of this XiqEmailLog.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this XiqEmailLog.

        The email log status  # noqa: E501

        :param status: The status of this XiqEmailLog.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XiqEmailLog):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, XiqEmailLog):
            return True

        return self.to_dict() != other.to_dict()
