# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 24.2.0.39
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from extremecloudiq.configuration import Configuration


class XiqAlertGroupCount(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'group_id': 'int',
        'group_name': 'str',
        'count': 'int'
    }

    attribute_map = {
        'group_id': 'group_id',
        'group_name': 'group_name',
        'count': 'count'
    }

    def __init__(self, group_id=None, group_name=None, count=None, local_vars_configuration=None):  # noqa: E501
        """XiqAlertGroupCount - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._group_id = None
        self._group_name = None
        self._count = None
        self.discriminator = None

        self.group_id = group_id
        if group_name is not None:
            self.group_name = group_name
        self.count = count

    @property
    def group_id(self):
        """Gets the group_id of this XiqAlertGroupCount.  # noqa: E501

        The group unique identifier  # noqa: E501

        :return: The group_id of this XiqAlertGroupCount.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this XiqAlertGroupCount.

        The group unique identifier  # noqa: E501

        :param group_id: The group_id of this XiqAlertGroupCount.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and group_id is None:  # noqa: E501
            raise ValueError("Invalid value for `group_id`, must not be `None`")  # noqa: E501

        self._group_id = group_id

    @property
    def group_name(self):
        """Gets the group_name of this XiqAlertGroupCount.  # noqa: E501

        The group name  # noqa: E501

        :return: The group_name of this XiqAlertGroupCount.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this XiqAlertGroupCount.

        The group name  # noqa: E501

        :param group_name: The group_name of this XiqAlertGroupCount.  # noqa: E501
        :type: str
        """

        self._group_name = group_name

    @property
    def count(self):
        """Gets the count of this XiqAlertGroupCount.  # noqa: E501

        The count of group  # noqa: E501

        :return: The count of this XiqAlertGroupCount.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this XiqAlertGroupCount.

        The count of group  # noqa: E501

        :param count: The count of this XiqAlertGroupCount.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and count is None:  # noqa: E501
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, XiqAlertGroupCount):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, XiqAlertGroupCount):
            return True

        return self.to_dict() != other.to_dict()
