# coding: utf-8

"""
    ExtremeCloud IQ API

    ExtremeCloud IQ RESTful API for external and internal applications.  # noqa: E501

    The version of the OpenAPI document: 25.2.0.123
    Contact: support@extremenetworks.com
    Generated by: https://openapi-generator.tech
"""

from extremecloudiq.paths.dashboard_wireless_usage_capacity_export.post import ExportToCsv
from extremecloudiq.paths.dashboard_wireless_usage_capacity_excessive_retries.post import GetCountExcessiveRetries
from extremecloudiq.paths.dashboard_wireless_usage_capacity_excessive_packet_loss.post import GetPacketLossExcessiveResponse
from extremecloudiq.paths.dashboard_wireless_usage_capacity_grid.post import GetUsageCapacityGrid
from extremecloudiq.paths.dashboard_wireless_usage_capacity_excessive_utilization.post import GetWirelessUsageCapacityExcessiveUtilization


class DashboardWirelessUsageAndCapacityApi(
    ExportToCsv,
    GetCountExcessiveRetries,
    GetPacketLossExcessiveResponse,
    GetUsageCapacityGrid,
    GetWirelessUsageCapacityExcessiveUtilization,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
